# -*- coding: utf-8 -*-
{
    'name': 'Website Pricing Plans',
    'version': '19.0.5.0.0',
    'category': 'Website',
    'summary': '',
    'author': 'Dana elkashef',
    'depends': ['website'],
    'data': [
        'security/ir.model.access.csv',
        'views/shared_components.xml',
        'views/pricing_plan_views.xml',
        'views/website_templates.xml',
        'data/pricing_plan_data.xml',
        'views/homepage_template1.xml',
        'views/all_features_template.xml',
        'views/contact_template.xml',
        'views/retail_template.xml',
        'views/clothing_template.xml',
        'views/perfume_template.xml',

    ],
    'assets': {
        'web.assets_frontend': [
            'website_pricing_plans/static/src/css/pricing.css',
            'website_pricing_plans/static/src/css/register.css',
            'website_pricing_plans/static/src/css/login.css',
            'website_pricing_plans/static/src/js/pricing.js',
            'website_pricing_plans/static/src/css/invoicing.css',
            'website_pricing_plans/static/src/js/invoicing.js',
            'website_pricing_plans/static/src/js/register.js',
            'website_pricing_plans/static/src/js/login.js',
            'website_pricing_plans/static/src/css/homepage.css',
            'website_pricing_plans/static/src/js/homepage.js',
            'website_pricing_plans/static/src/css/all_features.css',
            'website_pricing_plans/static/src/js/all_features.js',
            'website_pricing_plans/static/src/css/contact.css',
            'website_pricing_plans/static/src/css/retail.css',
            'website_pricing_plans/static/src/js/contact.js',
            'website_pricing_plans/static/src/js/retail.js',
            'website_pricing_plans/static/src/css/perfume.css',
            'website_pricing_plans/static/src/js/perfume.js',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
}
